server:
  port: 8888

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
  redis:
    database: 0
    port: 6379
    host: 192.168.31.30
